apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      group: apps
      kind: Deployment
      # name: default
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          nvidia.com/gpu.deploy.driver: 'true'
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests
        value:
          nvidia.com/gpu: 1
