apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: yolo-api-patch
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/redhat-na-ssa/flyingthings.git
  labels:
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
spec:
  output:
    to:
      kind: ImageStreamTag
      name: yolo-api:latest
  runPolicy: SerialLatestOnly
  source:
    contextDir: /source/yolo-api
    git:
      ref: main
      uri: https://github.com/redhat-na-ssa/flyingthings.git
    type: Git
  strategy:
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
