apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: yolo-api
  # app.kubernetes.io/component: yolo-api
  # app.kubernetes.io/instance: yolo-api
  app.kubernetes.io/name: yolo-api
  app.kubernetes.io/part-of: yolo-api

resources:
- bc-base-docker.yaml
- bc-base-source.yaml
- bc-patch.yaml
