apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: yolo-api
  # app.kubernetes.io/component: yolo-api
  # app.kubernetes.io/instance: yolo-api
  app.kubernetes.io/name: yolo-api
  app.kubernetes.io/part-of: yolo-api

resources:
- bc-base-via-docker.yaml
- bc-base-via-source.yaml
# - bc-embed-model-s2i.yaml
- bc-patch-video.yaml
- bc-python-s2i-patch.yaml
- is.yaml
