apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: shell-script
spec:
  results:
    - name: output
      description: Generic output you can use as a result
  params:
    - name: SCRIPT
      description: The bash script you want to run
      type: string
      default: |
        #!/usr/bin/env sh
        pwd && ls -l && id
        echo "SOURCE_DIR: ${SOURCE_DIR}" && ls -l "${SOURCE_DIR}"
        date | tee $(results.output.path)
    - name: IMAGE
      description: The image used to run the script
      type: string
      default: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    - name: INPUT
      description: Generic input for environment
      type: string
      default: ''
  steps:
    - name: run-script
      image: $(params.IMAGE)
      script: |
        $(params.SCRIPT)
      env:
        - name: SOURCE_DIR
          value: $(workspaces.source.path)
        - name: INPUT
          value: $(params.INPUT)
  workspaces:
    - name: source
      mountPath: /source
      optional: true
