apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: train-model-cpu
spec:
  params:
    - name: BATCH_SIZE
      type: string
    - name: NUM_EPOCHS
      type: string
    - name: WEIGHTS
      type: string
    - name: BASE_MODEL
      type: string
    - name: NAMESPACE
      type: string
    - name: IMAGE
      type: string
  steps:
    - name: train-model-using-cpu
      image: $(params.IMAGE)
      script: |
        cd $(workspaces.workspace.path)

        SOURCE_DIR=$(workspaces.source.path)
        BASEDIR=${SOURCE_DIR}/source/training-job

        source $(workspaces.source.path)/source/training/functions.sh && \
        model_training

        pwd && ls -al
      env:
        - name: BATCH_SIZE
          value: $(params.BATCH_SIZE)
        - name: NUM_EPOCHS
          value: $(params.NUM_EPOCHS)
        - name: WEIGHTS
          value: $(params.WEIGHTS)
        - name: BASE_MODEL
          value: $(params.BASE_MODEL)
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /usr/local/lib/python3.9/site-packages/yolov5/training
          name: training
  volumes:
    - name: dshm
      emptyDir:
          medium: Memory
          sizeLimit: 4Gi
    - name: training
      emptyDir: {}
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source