apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'flyingthings-notebook'
  annotations: {}
spec:
  selector:
    matchLabels:
      app: flyingthings
  replicas: 1
  template:
    metadata:
      labels:
        app: flyingthings
    spec:
      containers:
        - name: container
          image: yolo:latest
          # envFrom:
          #   - configMapRef:
          #       name: flyingthings-configmap
          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /mydata
              name: training-data
            - mountPath: /dev/shm
              name: dshm
          resources: {}
      volumes:
        - name: training-data
          persistentVolumeClaim:
            claimName: training-data
        - name: dshm
          emptyDir:
             medium: Memory
      imagePullSecrets: []
  strategy:
    type: Recreate
  paused: false
---
apiVersion: v1
kind: Service
metadata:
  name: flyingthings-svc
spec:
  selector:
    app: flyingthings
  ports:
    - protocol: TCP
      port: 8888
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: flyingthings-rt
  labels: {}
spec:
  to:
    kind: Service
    name: flyingthings-svc
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
  path: /
  port:
    targetPort: 8888
