apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: label-studio-pipeline
spec:
  params:
    - name: git-url
      default: git@git.davenet.local:/data/git-repos/flyingthings.git
      description: url of the git repo for the code of deployment
      type: string
    - name: git-revision
      default: djw
      description: revision to be used from repo of the code for deployment
      type: string
    - name: ocp-tablespace
      description: tablespace for the deployment
      default: modemo
      type: string
    - name: LABELSTUD_IMAGE
      default: image-registry.openshift-image-registry.svc:5000/$(params.ocp-tablespace)/labelstud:latest
      description: image for label studio
      type: string
    - name: LABELSTUD_DOCKERFILE
      default: source/labelstudio
      description: dockerfile path 
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
        - name: ssh-directory
          workspace: git-credentials
    - name: build-labelstudio
      params:
        - name: IMAGE
          value: $(params.LABELSTUD_IMAGE)
        - name: DOCKERFILE_PATH
          value: $(params.LABELSTUD_DOCKERFILE)          
        - name: DOCKERFILE
          value: $(workspaces.path)/$(params.LABELSTUD_DOCKERFILE)/Dockerfile
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: deploy-labelstudio
      taskSpec:
        steps:
          - name: oc-command
            image: quay.io/openshift/origin-cli:latest
            script: |
              oc apply -f $(workspaces.source.path)/source/labelstudio/pvc.yaml \
              && oc new-app image-registry.openshift-image-registry.svc:5000/modemo/labelstud:latest \
                --name=labelstudio \
              && oc set volume deployment/labelstudio \
                --add \
                --name=labelstudio-pvc \
                --type=persistentVolumeClaim \
                --claim-name=labelstudio-pvc \
                --mount-path=/opt/app-root/src/.local \
              && oc apply -f - <<EOF
              apiVersion: route.openshift.io/v1
              kind: Route
              metadata:
                name: labelstudio
                labels:
                  app: labelstudio
                  app.kubernetes.io/component: labelstudio
                  app.kubernetes.io/instance: labelstudio
              annotations:
                openshift.io/host.generated: "true"
              spec:
                to:
                  kind: Service
                  name: labelstudio
                  weight: 100
                port:
                  targetPort: 8080-tcp
                tls:
                  termination: edge
                  insecureEdgeTerminationPolicy: Allow
              EOF
      params:
      - name: ocp-tablespace
        value: $(params.ocp-tablespace)
      runAfter:
        - build-labelstudio
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
    - name: git-credentials
      description: My ssh credentials