apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: model-base
spec:
  params:
    - name: GIT_URL
      default: https://github.com/redhat-na-ssa/flyingthings.git
      description: url of the git repo for the code of deployment
      type: string
    - name: GIT_REVISION
      default: main
      description: revision to be used from repo of the code for deployment
      type: string
    - name: NAMESPACE
      default: ml-demo
      description: namespace for the deployment
      type: string
    - name: IMAGE_REGISTRY
      description: default image registry
      default: image-registry.openshift-image-registry.svc:5000
      type: string
    - name: YOLO_IMAGE
      default: $(params.IMAGE_REGISTRY)/$(params.NAMESPACE)/model-base:latest
      description: base image for yolo
      type: string
    - name: YOLO_CONTEXT
      default: source/yolov5
      description: dockerfile path
      type: string
    - name: YOLO_BUILD_ARGS
      default: --build-arg env=YOLOv5_VERSION=v7.0
      description: build arguments for yolo
      type: string
    - name: MODEL_IMAGE
      default: $(params.IMAGE_REGISTRY)/$(params.NAMESPACE)/model-server:latest
      description: model server image
      type: string
    - name: MODEL_CONTEXT
      default: source/model
      description: dockerfile path
      type: string
    - name: MODEL_BUILD_ARGS
      default: --build-arg WEIGHTS=flyingthings.pt --build-arg BASE_IMAGE=$(params.YOLO_IMAGE)
      description: build arguments for model server
      type: string
    - name: UBI_IMAGE
      default: $(params.IMAGE_REGISTRY)/$(params.NAMESPACE)/task-runner:latest
      description: base image for notebook
      type: string
    - name: UBI_CONTEXT
      default: source/task-runner
      description: dockerfile path
      type: string
    - name: BATCH_SIZE
      default: "2"
      type: string
    - name: NUM_EPOCHS
      default: "3"
      type: string
    - name: WEIGHTS
      default: "flyingthings.pt"
      type: string
    - name: BASE_MODEL
      default: "yolov5s.pt"
      type: string
    - name: MINIO_ENDPOINT
      default: "http://minio:9000"
      type: string
    - name: DATASET_ZIP
      default: "flyingthings-yolo.zip"
      type: string
    - name: MINIO_BUCKET
      default: "flyingthings"
      type: string
    - name: MINIO_ACCESSKEY
      default: "minioadmin"
      type: string
    - name: MINIO_SECRETKEY
      default: "minioadmin"
      type: string
    - name: MODEL_NAME
      default: model-pretrain
      description: name used to deploy the model and model server
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.GIT_REVISION)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: build-model-base
      params:
        - name: IMAGE
          value: $(params.YOLO_IMAGE)
        - name: CONTEXT
          value: $(params.YOLO_CONTEXT)
        - name: BUILD_EXTRA_ARGS
          value: "$(params.YOLO_BUILD_ARGS)"
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: build-task-runner
      params:
        - name: IMAGE
          value: $(params.UBI_IMAGE)
        - name: CONTEXT
          value: $(params.UBI_CONTEXT)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: create-bucket
      taskSpec:
        params:
          - name: SCRIPT
          - name: IMAGE
            default: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        steps:
          - name: debug
            image: $(params.IMAGE)
            script: |
              #!/usr/bin/env bash
              df -h && pwd && ls -al
          - name: run
            image: $(params.IMAGE)
            resources: {}
            script: |
              #!/usr/bin/env bash
              $(params.SCRIPT)
      params:
        - name: SCRIPT
          value: |
            MINIO_ENDPOINT=$(params.MINIO_ENDPOINT)
            MINIO_BUCKET=$(params.MINIO_BUCKET)
            MINIO_ACCESSKEY=$(params.MINIO_ACCESSKEY)
            MINIO_SECRETKEY=$(params.MINIO_SECRETKEY)

            source $(workspaces.source.path)/source/training/functions.sh && \
            minio_create_bucket ${MINIO_BUCKET}
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source
    - name: upload-artifacts
      taskSpec:
        params:
          - name: SCRIPT
          - name: IMAGE
            default: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        steps:
          - name: run
            image: $(params.IMAGE)
            resources: {}
            script: |
              #!/usr/bin/env bash
              $(params.SCRIPT)
      params:
        - name: SCRIPT
          value: |
            MINIO_ENDPOINT=$(params.MINIO_ENDPOINT)
            MINIO_BUCKET=$(params.MINIO_BUCKET)
            MINIO_ACCESSKEY=$(params.MINIO_ACCESSKEY)
            MINIO_SECRETKEY=$(params.MINIO_SECRETKEY)

            cd $(workspaces.source.path)

            source $(workspaces.source.path)/source/training/functions.sh && \
            minio_copy_artifacts
      runAfter:
        - fetch-repository
        - create-bucket
      workspaces:
        - name: source
          workspace: source
        - name: workspace
          workspace: shared-workspace
    - name: get-pretrained
      taskSpec:
        params:
          - name: SCRIPT
          - name: IMAGE
            default: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        steps:
          - name: run
            image: $(params.IMAGE)
            resources: {}
            script: |
              #!/usr/bin/env bash
              $(params.SCRIPT)
      params:
        - name: SCRIPT
          value: |
            MINIO_ENDPOINT=$(params.MINIO_ENDPOINT)
            MINIO_BUCKET=$(params.MINIO_BUCKET)
            MINIO_ACCESSKEY=$(params.MINIO_ACCESSKEY)
            MINIO_SECRETKEY=$(params.MINIO_SECRETKEY)
            BASE_MODEL=$(params.BASE_MODEL)

            cd $(workspaces.workspace.path)

            source $(workspaces.source.path)/source/training/functions.sh && \
            download_yolo_model && \
            minio_copy_yolo_model
      runAfter:
        - build-model-base
      workspaces:
        - name: source
          workspace: source
        - name: workspace
          workspace: shared-workspace
    - name: build-model-server
      params:
        - name: IMAGE
          value: $(params.MODEL_IMAGE)
        - name: CONTEXT
          value: $(params.MODEL_CONTEXT)
        - name: BUILD_EXTRA_ARGS
          value: "$(params.MODEL_BUILD_ARGS)"
      runAfter:
        - get-pretrained
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: deploy-model-server
      taskSpec:
        params:
          - name: SCRIPT
          - name: IMAGE
            default: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        steps:
          - name: run
            image: $(params.IMAGE)
            resources: {}
            script: |
              #!/usr/bin/env bash
              $(params.SCRIPT)
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - build-model-server
      params:
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      - name: SCRIPT
        value: |
          set -x
          
          oc new-app $(params.MODEL_IMAGE) \
            --name=$(params.MODEL_NAME) \
            --env=WEIGHTS=model_pretrained.pt \
            --env=MINIO_ENDPOINT=$(params.MINIO_ENDPOINT) \
            --env=MINIO_BUCKET=$(params.MINIO_BUCKET) \
            --env=MINIO_ACCESSKEY=$(params.MINIO_ACCESSKEY) \
            --env=MINIO_SECRETKEY=$(params.MINIO_SECRETKEY) \
            --env=BASE_MODEL=$(params.BASE_MODEL)
          
          oc apply -f - <<EOF
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: $(params.MODEL_NAME)
            labels:
              app: $(params.MODEL_NAME)
              app.kubernetes.io/component: $(params.MODEL_NAME)
              app.kubernetes.io/instance: $(params.MODEL_NAME)
          annotations:
            openshift.io/host.generated: "true"
          spec:
            to:
              kind: Service
              name: $(params.MODEL_NAME)
              weight: 100
            port:
              targetPort: 8000-tcp
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Allow
          EOF
          exit 0
    # - name: debug-workspace
    #   taskSpec:
    #     steps:
    #       - name: run-batch-file
    #         image: ubi9:latest
    #         script: |
    #           #!/usr/bin/env bash
    #           df -h && pwd && ls -al
    #   runAfter:
    #     - upload-artifacts
    #   workspaces:
    #     - name: workspace
    #       workspace: shared-workspace
  workspaces:
    - name: shared-workspace
    - name: source
