apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: model-base
spec:
  params:
    - name: GIT_URL
      default: https://github.com/redhat-na-ssa/flyingthings.git
      description: url of the git repo for the code of deployment
      type: string
    - name: GIT_REVISION
      default: main
      description: revision to be used from repo of the code for deployment
      type: string
    - name: NAMESPACE
      description: NAMESPACE for the deployment
      type: string
    - name: IMAGE_REGISTRY
      description: Default image registry
      default: image-registry.openshift-image-registry.svc:5000
      type: string
    - name: YOLO_IMAGE
      default: $(params.IMAGE_REGISTRY)/$(params.NAMESPACE)/yolo:latest
      description: base image for yolo
      type: string
    - name: YOLO_DOCKERFILE
      default: source/yolo
      description: dockerfile path 
      type: string
    - name: YOLO_BUILD_ARGS
      default: --build-arg env=YOLOv5_VERSION=7.0
      description: build arguments for yolo
      type: string
    - name: MODEL_IMAGE
      default: $(params.IMAGE_REGISTRY)/$(params.NAMESPACE)/custom-model:latest
      description: model server image
      type: string
    - name: MODEL_DOCKERFILE
      default: source/model
      description: dockerfile path 
      type: string
    - name: MODEL_BUILD_ARGS
      default: --build-arg WEIGHTS=flyingthings.pt --build-arg BASE_IMAGE=$(params.IMAGE_REGISTRY)/$(params.NAMESPACE)/yolo:latest
      description: build arguments for model server
      type: string
    - name: UBI_IMAGE
      default: $(params.IMAGE_REGISTRY)/$(params.NAMESPACE)/base-ubi9:latest
      description: base image for notebook
      type: string
    - name: UBI_DOCKERFILE
      default: source/ubi9
      description: dockerfile path 
      type: string
    - name: BATCH_SIZE
      default: "2"
      type: string
    - name: NUM_EPOCHS
      default: "3"
      type: string
    - name: WEIGHTS
      default: "flyingthings.pt"
      type: string
    - name: BASE_MODEL
      default: "yolov8n.pt"
      type: string
    - name: MINIO_ENDPOINT
      default: "http://minio:9000"
      type: string
    - name: DATASET_ZIP
      default: "flyingthings-yolo.zip"
      type: string
    - name: SIMPLEVIS_DATA
      default: "/opt/app-root/src/simplevis-data"
      type: string
    - name: BASEDIR
      default: "/opt/app-root/src"
      type: string
    - name: MINIO_BUCKET
      default: "flyingthings"
      type: string
    - name: PRETRAINED_BUCKET
      default: "yolo"
      type: string
    - name: MINIO_ACCESSKEY
      default: "minioadmin"
      type: string
    - name: MINIO_SECRETKEY
      default: "minioadmin"
      type: string
    - name: MINIO_CLIENT_URL
      default: "https://dl.min.io/client/mc/release/linux-amd64"
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.GIT_REVISION)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    # - name: debug-workspace
    #   taskSpec:
    #     steps:
    #       - name: run-batch-file
    #         image: ubi9:latest
    #         script: |
    #           #!/usr/bin/env bash
    #           echo "Let's see what we got here..." \
    #           && ls -al $(workspaces.workspace.path)
    #   runAfter:
    #     - upload-artifacts
    #   workspaces:
    #     - name: workspace
    #       workspace: shared-workspace
    - name: build-yolo
      params:
        - name: IMAGE
          value: $(params.YOLO_IMAGE)
        - name: CONTEXT
          value: $(params.YOLO_DOCKERFILE)          
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: YOLO_BUILD_ARGS
          value: "$(params.YOLO_BUILD_ARGS)"
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: build-ubi9
      params:
        - name: IMAGE
          value: $(params.UBI_IMAGE)
        - name: CONTEXT
          value: $(params.UBI_DOCKERFILE)          
        - name: DOCKERFILE
          value: ./Dockerfile
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: create-bucket
      taskRef:
        name: create-bucket
      params:
        - name: SIMPLEVIS_DATA
          value: "$(params.SIMPLEVIS_DATA)"
        - name: MINIO_ENDPOINT
          value: $(params.MINIO_ENDPOINT)
        - name: MINIO_BUCKET
          value: $(params.MINIO_BUCKET)
        - name: MINIO_ACCESSKEY
          value: $(params.MINIO_ACCESSKEY)
        - name: MINIO_SECRETKEY
          value: $(params.MINIO_SECRETKEY)
        - name: MINIO_CLIENT_URL
          value: $(params.MINIO_CLIENT_URL)
      workspaces:
        - name: source
          workspace: source
        - name: workspace
          workspace: shared-workspace
      runAfter:
        - fetch-repository
    - name: upload-artifacts
      taskRef:
        name: upload-artifacts
      params:
        - name: SIMPLEVIS_DATA
          value: "$(params.SIMPLEVIS_DATA)"
        - name: MINIO_ENDPOINT
          value: $(params.MINIO_ENDPOINT)
        - name: MINIO_BUCKET
          value: $(params.MINIO_BUCKET)
        - name: PRETRAINED_BUCKET
          value: $(params.PRETRAINED_BUCKET)
        - name: MINIO_ACCESSKEY
          value: $(params.MINIO_ACCESSKEY)
        - name: MINIO_SECRETKEY
          value: $(params.MINIO_SECRETKEY)
        - name: MINIO_CLIENT_URL
          value: $(params.MINIO_CLIENT_URL)
      runAfter:
        - fetch-repository
        - create-bucket
      workspaces:
        - name: source
          workspace: source
        - name: workspace
          workspace: shared-workspace
    - name: get-pretrained
      taskRef:
        name: get-pretrained
      params:
        - name: WEIGHTS
          value: $(params.WEIGHTS)
        - name: BASE_MODEL
          value: "$(params.BASE_MODEL)"
        - name: SIMPLEVIS_DATA
          value: "$(params.SIMPLEVIS_DATA)"
        - name: MINIO_ENDPOINT
          value: $(params.MINIO_ENDPOINT)
        - name: PRETRAINED_BUCKET
          value: $(params.PRETRAINED_BUCKET)
        - name: MINIO_ACCESSKEY
          value: $(params.MINIO_ACCESSKEY)
        - name: MINIO_SECRETKEY
          value: $(params.MINIO_SECRETKEY)
        - name: MINIO_CLIENT_URL
          value: $(params.MINIO_CLIENT_URL)
        - name: NAMESPACE
          value: $(params.NAMESPACE)
      runAfter:
        - build-yolo
      workspaces:
        - name: source
          workspace: source
        - name: workspace
          workspace: shared-workspace
    - name: build-model-server
      params:
        - name: IMAGE
          value: $(params.MODEL_IMAGE)
        - name: CONTEXT
          value: $(params.MODEL_DOCKERFILE)          
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: BUILD_EXTRA_ARGS
          value: "$(params.MODEL_BUILD_ARGS)"
      runAfter:
        - get-pretrained
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: deploy-model-server
      taskSpec:
        params:
          - name: SCRIPT
            type: string
          - name: IMAGE
            default: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          - name: BASE_MODEL            
            type: string
            description: Base model for training
        steps:
          - env:
              - name: HOME
                value: /tekton/home
            image: $(params.IMAGE)
            name: oc
            resources: {}
            script: |
              #!/usr/bin/env bash
              $(params.SCRIPT)
              exit 0
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - build-model-server
      params:
      - name: NAMESPACE
        value: $(params.NAMESPACE)
      - name: MINIO_ENDPOINT
        value: $(params.MINIO_ENDPOINT)
      - name: PRETRAINED_BUCKET
        value: $(params.PRETRAINED_BUCKET)
      - name: MINIO_ACCESSKEY
        value: $(params.MINIO_ACCESSKEY)
      - name: MINIO_SECRETKEY
        value: $(params.MINIO_SECRETKEY)
      - name: MINIO_CLIENT_URL
        value: $(params.MINIO_CLIENT_URL)
      - name: BASE_MODEL
        value: $(params.BASE_MODEL)
      - name: SCRIPT
        value: |
          oc new-app $(params.IMAGE_REGISTRY)/$(params.NAMESPACE)/custom-model:latest \
            --name=model-yolo \
            --env=WEIGHTS=model_pretrained.pt \
            --env=SIMPLEVIS_DATA=/opt/app-root/src/simplevis-data \
            --env=MINIO_ENDPOINT=$(params.MINIO_ENDPOINT) \
            --env=MINIO_CLIENT_URL=$(params.MINIO_CLIENT_URL) \
            --env=MINIO_BUCKET=$(params.PRETRAINED_BUCKET) \
            --env=MINIO_ACCESSKEY=$(params.MINIO_ACCESSKEY) \
            --env=MINIO_SECRETKEY=$(params.MINIO_SECRETKEY) \
            --env=BASE_MODEL=$(params.BASE_MODEL)
          
          oc set volume deployment/model-yolo \
            --add \
            --name=simplevis-data-volume \
            --type=emptyDir \
            --mount-path=/opt/app-root/src/simplevis-data \
            --overwrite
          
          oc apply -f - <<EOF
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: model-yolo
            labels:
              app: model-yolo
              app.kubernetes.io/component: model-yolo
              app.kubernetes.io/instance: model-yolo
          annotations:
            openshift.io/host.generated: "true"
          spec:
            to:
              kind: Service
              name: model-yolo
              weight: 100
            port:
              targetPort: 8000-tcp
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Allow
          EOF
  workspaces:
    - name: shared-workspace
    - name: source