apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# patches:
#   - +      nodeSelector:
# +        nvidia.com/gpu.deploy.driver: 'true'
# +          resources:
# +            limits:
# +              nvidia.com/gpu: 1
